# Generated by Django 5.0.1 on 2024-07-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='url_image',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
